name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Nginx
        run: | 
          echo "${{ secrets.NGINX_PASSWORD }}" | sudo -S apt-get update
          sudo apt-get install nginx -y
          sleep 5  # Wait for Nginx to be installed completely
          sudo systemctl start nginx
          sudo systemctl enable nginx

      - name: Deploy to Local Nginx
        run: |
          echo "${{ secrets.NGINX_PASSWORD }}" | sudo -S cp -r dist/* /var/www/html/
          sudo systemctl restart nginx
        env:
          NGINX_PASSWORD: ${{ secrets.NGINX_PASSWORD }}
